### ISSUE TITLE
Basename command not available on Windows

### ISSUE THREAD

**Issue by NickeManarin** [Rolanddoda/vue-cli-plugin-gh-pages-auto-deploy#2]
I'm getting an exception when installing this package on my project.

```
-  Running completion hooks... ERROR  Error: Command failed with ENOENT: basename -s .git https://github.com/NickeManarin/Project-Name.git
spawn basename ENOENT
'basename' is not recognized as an internal or external command,
operable program or batch file.

Error: Command failed with ENOENT: basename -s .git https://github.com/NickeManarin/Project-Name.git
spawn basename ENOENT
'basename' is not recognized as an internal or external command,
operable program or batch file.
    at notFoundError (C:\fake-path\node_modules\vue-cli-plugin-gh-pages-auto-deploy\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\fake-path\node_modules\vue-cli-plugin-gh-pages-auto-deploy\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\fake-path\node_modules\vue-cli-plugin-gh-pages-auto-deploy\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Basically, looks like `basename` is an Unix exclusive command.

**Comment by Rolanddoda** [comment]
@NickeManarin thanks for filling out this issue.
In my end `basename` is a recognized  command:

![image](https://user-images.githubusercontent.com/18482346/84188514-0391f400-aa94-11ea-8d10-b6738cdfd04c.png)

However, this is a bug since not everyone has enabled Linux bash shell on Windows.

I have fixed the issue and should be working fine now. Please try and let me know if you get any error.

**Comment by NickeManarin** [comment]
It works. Thanks.
